mantisbt:
  image: vimagick/mantisbt:latest
  ports:
    - "8989:80"
  links:
    - postgres
  restart: always
postgres:
  image: postgres:9.5
  volumes:
  - ~/.postgres/data:/var/lib/postgresql/data
  environment:
  - POSTGRES_DB=rii_mantis
  - POSTGRES_USER=user
  - POSTGRES_PASSWORD=user
  restart: always