mantisbt:
  image: vimagick/mantisbt:latest
  ports:
    - "8989:80"
  links:
    - postgres
  restart: always

mysql:
  image: mysql:5.7
  volumes:
    - ./data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantis
    - MYSQL_PASSWORD=mantis
  restart: always
postgres:
  image: postgres:9.5
  volumes:
  - ~/.postgres/data:/var/lib/postgresql/data
  environment:
  - POSTGRES_DB=rii_mantis
  - POSTGRES_USER=user
  - POSTGRES_PASSWORD=user
  restart: always